scurvy <- read.table("scurvy.csv", sep = ",", header = TRUE)
summary(scurvy)
scurvy$treatment <- as.factor(scurvy$treatment)
scurvy$gum_rot_d6 <- as.factor(scurvy$gum_rot_d6)
scurvy$skin_sores_d6 <- as.factor(scurvy$skin_sores_d6)
scurvy$weakness_of_the_knees_d6 <- as.factor(scurvy$weakness_of_the_knees_d6)
scurvy$lassitude_d6 <- as.factor(scurvy$lassitude_d6)
scurvy$fit_for_duty_d6 <- as.factor(scurvy$fit_for_duty_d6)
scurvy$study_id <- as.character(scurvy$study_id)
scurvy$dosing_regimen_for_scurvy <- as.character(scurvy$dosing_regimen_for_scurvy)
View(scurvy)
scurvy_gum_rot <- table(scurvy$treatment, scurvy$gum_rot_d6)
scurvy_knee <- table(scurvy$treatment, scurvy$weakness_of_the_knees_d6)
scurvy_skin<-table(scurvy$treatment, scurvy$skin_sores_d6)
plot(scurvy_gum_rot)
View(scurvy_gum_rot)
scurvy_merged_symptoms <- merge(scurvy_gum_rot, scurvy_knee, scurvy_skin, )